// Authoring guide for the `workflow action=run` path — opencode's adaptation of
// Claude Code's `Workflow` tool description. The calling agent reads this (it is
// embedded in the tool DESCRIPTION) and authors a self-contained script inline; the
// loader's transform wraps it into the engine's run(args, ctx) module. Kept close to
// Claude's prose, adapted to opencode: global hooks (no ctx), agent types
// build/general/explore, USD budget, and no nested-workflow/worktree/resume.

export const SCRIPT_AUTHORING_GUIDE = [
  "AUTHORING A WORKFLOW SCRIPT (action=run):",
  "You write a self-contained orchestration script and it runs as a background multi-agent workflow. Reach for this to be comprehensive (decompose and cover in parallel), to be confident (independent perspectives + adversarial checks before committing), or to take on scale one context can't hold.",
  "Writing the full script is expected. Do not decide it is too heavy, do not switch to `generate` to avoid authoring it, and do not inspect an older workflow instead of starting the requested one. Write a simple valid script, run it, then fix gate/runtime errors if they happen.",
  "A requested workflow should default to multi-agent orchestration: several specialized agents, parallel tracks, staged pipelines, independent review, synthesis, adversarial verification, or iteration. Do not create a one-agent workflow unless the user explicitly asks for a single-step workflow.",
  "Do not be timid about using the agents needed for correctness, coverage, and independent review. Limits are for keeping work well-structured and context-safe, not token thrift.",
  "NEVER set the workflow tool's `budget` parameter unless the user explicitly asks for a dollar/cost cap. Do not invent budgets to save tokens. When no budget is set, the run is unlimited.",
  "Do not use `schema` by default, and never claim a schema is needed merely because outputs should be structured. Prefer plain text or explicit JSON-in-text instructions; schema can fail, so use it only when later workflow code truly needs validated fields and the model route supports forced structured output.",
  "After the workflow run starts, times out, finishes, or sends a completion bubble, read the workflow source file that actually ran before interpreting the result or replying to the user.",
  "",
  "SHAPE — a literal `meta` followed by a free top-level body:",
  "    export const meta = {",
  "      name: 'find-flaky-tests',",
  "      description: 'Find flaky tests and propose fixes',",
  "      phases: ['scan', 'fix'],          // optional; labels must match phase() calls",
  "    } as const",
  "",
  "    phase('scan')",
  "    const findings = await parallel(['unit logs', 'integration logs'].map(scope => () => agent(`Find flaky tests in ${scope}. Return concise bullets.`, { agentType: 'explore' })))",
  "    const fixes = await pipeline(findings.filter(Boolean), f => agent(`Propose fixes for these flakes. Do not edit files.\\n${f}`, { agentType: 'build' }))",
  "    return { fixes: fixes.filter(Boolean) }",
  "",
  "`meta` MUST be a pure literal (no variables, calls, spreads, or template interpolation) — it is read statically without running your code. `as const` is fine. The body runs AS the workflow: top-level `await` and `return` work; the returned value is the workflow result.",
  "",
  "GLOBALS available in the body — do NOT import anything, and there is no `ctx`; you may not touch `process`/`fs`/`fetch`/`eval`/`Bun`/`globalThis`:",
  "- agent(prompt, opts?) -> Promise<string>. Spawns ONE full autonomous OpenCode subagent — a full tool-using agent that can read/write files if permissions allow, run commands, and ITERATE until the task is done; NOT a single completion. It is expected to PERSIST and self-correct: if its work breaks (code won't compile, a command fails, a test is red) it debugs and fixes rather than returning 'it's broken'. Returns its final text. opts = { agentType?: 'build'|'general'|'explore', model?: string, schema?: object }. `schema` is optional and risky: it FORCES structured output and can fail on thinking-enabled model routes that reject forced tool use. Do not use schema by default; use plain text/JSON instructions unless later code truly needs a validated object. agentType: 'build' = writing/code, 'general' = synthesis/judging, 'explore' = research/finding files; omit for the default agent. NEVER use 'plan' (interactive — it stalls a headless run).",
  "- parallel(thunks) -> Promise<(T|null)[]>. Run thunks `() => Promise<T>` concurrently and await ALL (a BARRIER). A failed arm resolves to `null`, never throws — `.filter(Boolean)` before use.",
  "- pipeline(items, stage1, stage2, ...) -> Promise<(Last|null)[]>. Each item flows through ALL stages independently with NO barrier between stages (item B can be in stage 3 while item A is still in stage 1). Each stage is `(prev, item, index) => Promise`. At most 8 stages. A stage that throws drops THAT item to `null`. THIS IS THE DEFAULT for multi-stage work.",
  "- phase(label) / log(message) -> progress UI. `label` should be one of meta.phases.",
  "- args -> the workflow's input arguments object.",
  "- budget -> read-only telemetry `{ total, spent(), remaining() }` in USD. `total` is null when unbudgeted. Only branch on budget when the user explicitly requested a dollar/cost cap; otherwise ignore it and never add budget-throttled loops or guards.",
  "- Also available (opencode helpers): synthesize, adversarial, loop (maxIterations clamped to 1..100), forEach. Nested workflow() is NOT supported — author a single workflow.",
  "",
  "DEFAULT TO pipeline(). Use a barrier (parallel between stages) ONLY when stage N genuinely needs ALL of stage N-1 — dedup/merge across the full result set, early-exit when the count is zero, or cross-item comparison. 'I need to flatten/map/filter first' is NOT a barrier reason; do it inside a pipeline stage.",
  "",
  "AGENT BOUNDARIES — because agent() is autonomous, prompts must say what not to do. Unless the objective explicitly asks for repository changes or artifacts, subagents must not create or edit files; they should return findings in text. Subagents must not ask the user clarifying questions; tell them to choose reasonable assumptions and continue, or return `BLOCKED:` with the exact missing information. For research, bound source count and output size in the prompt, but understand these are quality/context controls, not hard runtime budgets.",
  "",
  "LARGE FAN-IN — for large fan-in with more than 8 substantive outputs, use a tree: researchers -> group summaries -> reviewers/judges -> final editor. The runtime clips long synthesize inputs, but clipping is a safety rail; it is not a substitute for designing a good synthesis hierarchy.",
  "",
  "WORKFLOW DEFAULTS — the point of a workflow is orchestration. Start by decomposing the objective into independent angles, files, components, hypotheses, failures, or candidate fixes; run those tracks through parallel(), pipeline(), or forEach(); then use separate synthesis/review agents to reconcile the results.",
  "Scale to the request: 'find any bugs' -> a few finders + independent verification + synthesis; 'thoroughly audit this' -> a larger finder pool, a 3-5 vote adversarial pass, grouped synthesis, then a final editor. A single agent is only appropriate when the user explicitly asks for a single-step workflow.",
  "",
  "PATTERNS (compose from the primitives):",
  "- Adversarial verify: spawn N independent skeptics per finding, each prompted to REFUTE; drop the finding if a majority refute. Stops plausible-but-wrong findings surviving.",
  "- Judge panel: generate N independent attempts from different angles, score with parallel judges, synthesize from the winner.",
  "- Loop-until-dry: keep spawning finders until K consecutive rounds surface nothing new.",
  "- Multi-modal sweep: parallel agents each searching a different way (by name, by content, by usage).",
  "",
  "Canonical multi-stage shape — each dimension verifies as soon as its review lands. This uses plain text and does not need schema:",
  "    const results = await pipeline(",
  "      DIMENSIONS,",
  "      d => agent(d.prompt + '\\nReturn 3-5 compact findings as bullets with evidence.'),",
  "      findings => parallel(['severity', 'evidence', 'novelty'].map(lens => () =>",
  "        agent(`Review these findings for ${lens}. Return KEEP/DROP notes with evidence.\\n${findings}`))),",
  "      reviews => agent(`Synthesize the kept findings into a final concise report.\\n${reviews.filter(Boolean).join('\\n\\n')}`),",
  "    )",
  "    return results.filter(Boolean).join('\\n\\n')",
  "",
  "The script runs in the BACKGROUND — `run` returns immediately and a completion bubble + result are injected when it finishes (watch live with /workflows). Author the script yourself; do not call `generate` merely because the script is long or needs careful quoting.",
].join("\n")

export * as ScriptPrompt from "./script-prompt"
